### ISSUE TITLE
KeyError: 'GET_INVENTORY'

### ISSUE THREAD

**Issue by pedromntomas** [traversc/getPokeStats#6]
Hey, I'm getting the following error when running the script:
```python
Traceback (most recent call last):
  File "getPokeStats.py", line 29, in <module>
    items = response['responses']['GET_INVENTORY']['inventory_delta']['inventory_items']
KeyError: 'GET_INVENTORY'
```
I've serch a bit for this error and it means the key doesn't exists in response['responses'] array.
Probably the response from pogo api is empty, or something similar.
Any idea why? Thanks!

**Comment by traversc** [comment]
Apologies, I stopped playing the game and haven't been keeping track of pgo development.  You may have better luck looking for a solution on r/pokemongodev.  Good luck.
